"""Integration tests for the Alembic migration lifecycle."""

from collections.abc import Iterator
from contextlib import contextmanager
from uuid import uuid4

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from psycopg import connect
from sqlalchemy import Column, Integer, Table
from sqlalchemy.engine import make_url

from devstash.core.config import get_settings
from devstash.core.database import Base

MIGRATION_HEAD = "20260901_0005"


def _alembic_config() -> Config:
    return Config("alembic.ini")


def _direct_connection_url(database_url: str) -> str:
    return (
        make_url(database_url)
        .set(drivername="postgresql")
        .render_as_string(hide_password=False)
    )


@contextmanager
def _migration_database(
    database_url: str,
    monkeypatch: pytest.MonkeyPatch,
) -> Iterator[None]:
    monkeypatch.setenv("DATABASE_URL", database_url)
    get_settings.cache_clear()
    try:
        yield
    finally:
        get_settings.cache_clear()


def _current_revision(database_url: str) -> str | None:
    with connect(_direct_connection_url(database_url)) as connection:
        result = connection.execute("SELECT version_num FROM alembic_version")
        row = result.fetchone()
    return None if row is None else str(row[0])


def _items_table_exists(database_url: str) -> bool:
    with connect(_direct_connection_url(database_url)) as connection:
        result = connection.execute("SELECT to_regclass('public.items') IS NOT NULL")
        row = result.fetchone()
        if row is None:
            raise AssertionError("Expected the table-existence query to return a row")
        return bool(row[0])


def _table_exists(database_url: str, table_name: str) -> bool:
    with connect(_direct_connection_url(database_url)) as connection:
        result = connection.execute(
            "SELECT to_regclass(%s) IS NOT NULL", (f"public.{table_name}",)
        )
        row = result.fetchone()
        if row is None:
            raise AssertionError("Expected the table-existence query to return a row")
        return bool(row[0])


def _column_is_nullable(database_url: str, table_name: str, column_name: str) -> bool:
    with connect(_direct_connection_url(database_url)) as connection:
        result = connection.execute(
            """
            SELECT is_nullable
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = %s
            """,
            (table_name, column_name),
        )
        row = result.fetchone()
        if row is None:
            raise AssertionError(f"Expected {table_name}.{column_name} to exist")
        return str(row[0]) == "YES"


def _item_constraint_names(database_url: str) -> set[str]:
    with connect(_direct_connection_url(database_url)) as connection:
        result = connection.execute(
            """
            SELECT conname
            FROM pg_constraint
            WHERE conrelid = 'public.items'::regclass
            """
        )
        return {str(row[0]) for row in result.fetchall()}


def _item_index_names(database_url: str) -> set[str]:
    with connect(_direct_connection_url(database_url)) as connection:
        result = connection.execute(
            """
            SELECT indexname
            FROM pg_indexes
            WHERE schemaname = 'public' AND tablename = 'items'
            """
        )
        return {str(row[0]) for row in result.fetchall()}


def test_migrations_upgrade_downgrade_and_return_to_head(
    database_url: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    with _migration_database(database_url, monkeypatch):
        config = _alembic_config()

        command.upgrade(config, "head")
        assert _current_revision(database_url) == MIGRATION_HEAD
        assert _items_table_exists(database_url)
        assert _table_exists(database_url, "users")
        assert _table_exists(database_url, "auth_sessions")
        assert _table_exists(database_url, "auth_rate_limits")
        assert not _column_is_nullable(database_url, "items", "owner_id")
        assert {
            "ck_items_item_type_valid",
            "ck_items_title_not_blank",
            "ck_items_content_not_blank",
            "ck_items_language_for_snippet",
            "pk_items",
        } <= _item_constraint_names(database_url)
        assert "ix_items_updated_at_id" in _item_index_names(database_url)
        assert "ix_items_search_vector" in _item_index_names(database_url)
        assert "ix_items_owner_updated_at_id" in _item_index_names(database_url)

        command.downgrade(config, "base")
        assert _current_revision(database_url) is None
        assert not _items_table_exists(database_url)

        command.upgrade(config, "head")
        assert _current_revision(database_url) == MIGRATION_HEAD
        assert _items_table_exists(database_url)


def test_legacy_items_require_explicit_owner_mapping(
    database_url: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    with _migration_database(database_url, monkeypatch):
        config = _alembic_config()
        command.downgrade(config, "20260828_0003")
        item_id = uuid4()

        with connect(_direct_connection_url(database_url)) as connection:
            connection.execute(
                """
                INSERT INTO items (id, title, content, item_type)
                VALUES (%s, 'Legacy item', 'Preserve me', 'note')
                """,
                (item_id,),
            )
            connection.commit()

        command.upgrade(config, "20260901_0004")
        with pytest.raises(RuntimeError, match="explicit owner mapping"):
            command.upgrade(config, "head")

        assert _current_revision(database_url) == "20260901_0004"
        assert _column_is_nullable(database_url, "items", "owner_id")

        owner_id = uuid4()
        with connect(_direct_connection_url(database_url)) as connection:
            connection.execute(
                """
                INSERT INTO users (id, email, password_hash)
                VALUES (%s, 'legacy-owner@example.com', 'migration-only-hash')
                """,
                (owner_id,),
            )
            connection.execute(
                "UPDATE items SET owner_id = %s WHERE id = %s",
                (owner_id, item_id),
            )
            connection.commit()

        command.upgrade(config, "head")
        assert _current_revision(database_url) == MIGRATION_HEAD
        assert not _column_is_nullable(database_url, "items", "owner_id")


def test_alembic_check_detects_metadata_drift(
    database_url: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    unexpected_table = Table(
        "unexpected_model",
        Base.metadata,
        Column("id", Integer, primary_key=True),
    )

    try:
        with _migration_database(database_url, monkeypatch):
            config = _alembic_config()
            command.upgrade(config, "head")

            with pytest.raises(AutogenerateDiffsDetected):
                command.check(config)
    finally:
        Base.metadata.remove(unexpected_table)

    with _migration_database(database_url, monkeypatch):
        command.check(_alembic_config())
