"""Integration tests for the Alembic migration lifecycle."""

from collections.abc import Iterator
from contextlib import contextmanager

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from psycopg import connect
from sqlalchemy import Column, Integer, Table
from sqlalchemy.engine import make_url

from devstash.core.config import get_settings
from devstash.core.database import Base

MIGRATION_HEAD = "20260825_0001"


def _alembic_config() -> Config:
    return Config("alembic.ini")


def _direct_connection_url(database_url: str) -> str:
    return (
        make_url(database_url)
        .set(drivername="postgresql")
        .render_as_string(hide_password=False)
    )


@contextmanager
def _migration_database(
    database_url: str,
    monkeypatch: pytest.MonkeyPatch,
) -> Iterator[None]:
    monkeypatch.setenv("DATABASE_URL", database_url)
    get_settings.cache_clear()
    try:
        yield
    finally:
        get_settings.cache_clear()


def _current_revision(database_url: str) -> str | None:
    with connect(_direct_connection_url(database_url)) as connection:
        result = connection.execute("SELECT version_num FROM alembic_version")
        row = result.fetchone()
    return None if row is None else str(row[0])


def test_migrations_upgrade_downgrade_and_return_to_head(
    database_url: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    with _migration_database(database_url, monkeypatch):
        config = _alembic_config()

        command.upgrade(config, "head")
        assert _current_revision(database_url) == MIGRATION_HEAD

        command.downgrade(config, "base")
        assert _current_revision(database_url) is None

        command.upgrade(config, "head")
        assert _current_revision(database_url) == MIGRATION_HEAD


def test_alembic_check_detects_metadata_drift(
    database_url: str,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    unexpected_table = Table(
        "unexpected_model",
        Base.metadata,
        Column("id", Integer, primary_key=True),
    )

    try:
        with _migration_database(database_url, monkeypatch):
            config = _alembic_config()
            command.upgrade(config, "head")

            with pytest.raises(AutogenerateDiffsDetected):
                command.check(config)
    finally:
        Base.metadata.remove(unexpected_table)

    with _migration_database(database_url, monkeypatch):
        command.check(_alembic_config())
